# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" # Monitors your package.json
    directory: "/"
    schedule:
      interval: "weekly" # Checks every week
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions" # Monitors your workflow files
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3